# -*- coding: utf-8 -*-
"""counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-U1K7WjKl8PNrko0YvIETKExbKiMctpT
"""

enter_score=input("請輸入一串成績")
score=enter_score.split()
count=0

for i in score:
  if int(i)<60:
    count+=1
print("不及格人數", count)

print("分數最大值", max(score))
print("分數最小值", min(score))