# -*- coding: utf-8 -*-
"""counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-U1K7WjKl8PNrko0YvIETKExbKiMctpT
"""

enter_score=input("請輸入一串成績")
score=enter_score.split()

for i in score:
  if int(i)<60:
    print(i,end =" ")

print("分數平均:", sum(int(i) for i in score) / len(score))